# Passphrase: Arturonivura_1982

default_platform(:ios)

platform :ios do
  desc "Archive for production"
  lane :archive_production do
    archive(
      configuration: "Release",
      scheme: "prod"
    )
  end 

  desc "Archive for scheme and build configuration"
  lane :archive do |options|
    increment_build_number(
      build_number: ENV['BITRISE_BUILD_NUMBER'],
    )
    
    # This are done in the bitrise workflow
    # match(type: "appstore")
    # cocoapods

    gym(
      workspace: ENV['WORKSPACE_PATH'],
      configuration: options[:configuration],
      scheme: options[:scheme],
      clean: true,
      include_bitcode: false
    )
  end

  desc "Upload to AppStoreConnect and deploy to TestFlight"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: "3PSFM6973T",
      issuer_id: "eef01e0b-9389-48e1-9f14-67a1d1fa2f19",
      key_filepath: ENV['APPSTORE_API_KEY_PATH'],
      duration: 1200,
      in_house: false
    )

    pilot(
      changelog: "Bug Fixes.",
      skip_waiting_for_build_processing: false,
      api_key: api_key
    )

    clean_build_artifacts
  end

  desc "Run unit tests for production"
  lane :execute_tests_production do |options|
    execute_tests(
      scheme: "prod"
    )
  end

  desc "Run unit tests"
  lane :execute_tests do |options|
    scan(
      workspace: ENV['WORKSPACE_PATH'],
      scheme: options[:scheme],
      destination: "platform=iOS Simulator,name=iPhone 8,OS=latest",
      clean: true
    )
  end

  desc "Create the bundle id and the application"
  lane :register_app do
    produce(
      username: "marco.maddalena1982@gmail.com",
      app_identifier: "io.marco.maddalena.fastlane.cicd.test",
      app_name: "FastlaneCicdTest"
    )
  end

  desc "Commit version bump"
  lane :commit_bump do
    commit_version_bump(
      message: "Fastlane iOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]} [ci ckip]",
      xcodeproj: ENV['WORKSPACE_PATH'],
      force: true
    )
  end
end
