# Passphrase: Arturonivura_1982

default_platform(:ios)

platform :ios do
  desc "Archive for production"
  lane :archive_production do
    archive(
      configuration: "Release-prod",
      scheme: "prod"
    )
  end

  lane :archive_stage do
    archive(
      configuration: "Release-stage",
      scheme: "stage"
    )
  end 

  desc "Archive for scheme and build configuration"
  lane :archive do |options|
    increment_build_number(
      build_number: ENV['BITRISE_BUILD_NUMBER'],
    )
    
    # This are done in the bitrise workflow
    # match(
    #   type: "appstore",
    #   app_identifier "io.marco.maddalena.fastlane.cicd.test"
    # )
    # cocoapods

    gym(
      workspace: ENV['WORKSPACE_PATH'],
      configuration: options[:configuration],
      scheme: options[:scheme],
      clean: true,
      include_bitcode: false
    )
  end

  desc "Upload to AppStoreConnect and deploy to TestFlight"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: "3PSFM6973T",
      issuer_id: "eef01e0b-9389-48e1-9f14-67a1d1fa2f19",
      key_filepath: ENV['APPSTORE_API_KEY_PATH'],
      duration: 1200,
      in_house: false
    )

    pilot(
      changelog: "Bug Fixes.",
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )

    clean_build_artifacts
  end

  desc "Run unit tests for production"
  lane :execute_tests_production do |options|
    execute_tests(
      scheme: "prod"
    )
  end

  desc "Run unit tests"
  lane :execute_tests do |options|
    scan(
      workspace: ENV['WORKSPACE_PATH'],
      scheme: options[:scheme],
      destination: "platform=iOS Simulator,name=iPhone 8,OS=latest",
      clean: true
    )
  end

  desc "Create the bundle id and the application"
  lane :register_app do |options|
    produce(
      username: "marco.maddalena1982@gmail.com",
      app_identifier: options[:app_identifier],
      app_name: options[:app_name]
    )
  end

  desc "Create production FastlaneCicdTest app"
  lane :register_app_production do
    register_app(
      app_identifier: "io.marco.maddalena.fastlane.cicd.test",
      app_name: "FastlaneCicdTest"
    )
  end

  desc "Create stage FastlaneCicdTest app"
  lane :register_app_stage do
    produce(
      app_identifier: "io.marco.maddalena.fastlane.cicd.test.stage",
      app_name: "FastlaneCicdTestStage"
    )
  end

  desc "Create appstore certificates and profiles for app_id"
  lane :create_appstore_cert_and_profile do |options|
    match(
      type: "appstore",
      app_identifier: options[:app_identifier]
    )
  end

  desc "Create appstore certificates and profiles for FastlaneCicdTest app"
  lane :create_appstore_cert_and_profile_prod do
    create_appstore_cert_and_profile(
      app_identifier: "io.marco.maddalena.fastlane.cicd.test"
    )
  end

  desc "Create appstore certificates and profiles for FastlaneCicdTestStage app"
  lane :create_appstore_cert_and_profile_stage do
    create_appstore_cert_and_profile(
      app_identifier: "io.marco.maddalena.fastlane.cicd.test.stage"
    )
  end

  desc "Create development certificates and profiles for app_id"
  lane :create_development_cert_and_profile do |options|
    match(
      type: "development",
      app_identifier: options[:app_identifier]
    )
  end

  desc "Create development certificates and profiles for FastlaneCicdTest app"
  lane :create_development_cert_and_profile_prod do
    create_development_cert_and_profile(
      app_identifier: "io.marco.maddalena.fastlane.cicd.test"
    )
  end

  desc "Create development certificates and profiles for FastlaneCicdTestStage app"
  lane :create_development_cert_and_profile_stage do
    create_development_cert_and_profile(
      app_identifier: "io.marco.maddalena.fastlane.cicd.test.stage"
    )
  end

  desc "Commit version bump"
  lane :commit_bump do
    commit_version_bump(
      message: "Fastlane iOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]} [ci ckip]",
      xcodeproj: ENV['WORKSPACE_PATH'],
      force: true
    )
  end
end
